version: 2

models:
  - name: dim_pessoas
    description: "Dimensão com informações das pessoas para análises."
    columns:
      - name: id_pessoa
        description: "Chave substituta para a pessoa."
      - name: nome
        description: "Nome completo da pessoa."
      - name: sexo
        description: "Gênero da pessoa."
      - name: dt_nasc
        description: "Data de nascimento da pessoa."

  - name: dim_produtos
    description: "Dimensão com informações dos produtos para análises."
    columns:
      - name: id_produto
        description: "Chave substituta para o produto."
      - name: descricao
        description: "Descrição do produto."
      - name: cat_desc
        description: "Descrição da categoria do produto."

  - name: fato_pedidos
    description: "Fato principal contendo dados dos pedidos realizados."
    columns:
      - name: id_pedido
        description: "Chave substituta para o pedido."
      - name: id_pessoa
        description: "Chave substituta referenciando a pessoa."
      - name: id_produto
        description: "Chave substituta referenciando o produto."
      - name: dt_venda
        description: "Data da venda."
      - name: dispositivo
        description: "Dispositivo usado na venda."
      - name: geohash
        description: "Geolocalização da venda."
      - name: valor_unit
        description: "Valor unitário da venda."